service:
    post: 8080

mybatis:
    mapperLocations: classpath:Mybatis/*.xml
    typeAliasesPackage: com.dwizero.Bean.VO
    ConfigLocation: classpath:Mybatis-Config.xml
spring:
#用来标识使用那个application-{}.properties
    profiles:
        active: local
    http:
        multipart:
            maxFileSize: 100Mb
            maxRequestSize: 100Mb
    redis:
        host: 192.168.68.128
        port: 6379
    rabbitmq:
        addresses: 192.168.68.128:5672
        username: admin
        password: admin

#logging:
#    level:
#        com.dwizero: DEBUG
#    file: ./logs/core.log
#    root: INFO